#!/hint/bash

PRF="${HOME}/dotfiles/bash/"
[ -f "${PRF}environment" ]  && . "${PRF}environment"
[ -f "${PRF}path" ]         && . "${PRF}path"
unset PRF

[ -f "${HOME}/.local/bash" ] && . "${HOME}/.local/bash"

MY_BASH_ENV_IS_SET=true

# Source rc file for interactive login shells
[[ $- == *i* && -n CALLING_FROM_RC ]] && . ~/.bashrc
