#!/usr/bin/env bash

# Avoid recursive invocation
[ -n "$BASHRC_DISPATCH_PID" ] && [ $$ -eq "$BASHRC_DISPATCH_PID" ] && return
BASHRC_DISPATCH_PID=$$

# Run everything
PRF="${HOME}/dotfiles/bash/"
[ -f "${PRF}environment" ]  && . "${PRF}environment"
[ -f "${PRF}aliases" ]      && . "${PRF}aliases"
[ -f "${PRF}prompt" ]       && . "${PRF}prompt"
[ -f "${PRF}completion" ]   && . "${PRF}completion"
[ -f "${PRF}path" ]         && . "${PRF}path"

# Unset local variables
unset PRF
unset BASHRC_DISPATCH_PID
