#!/hint/bash

# Make sure my standard environment is set up. This should only be necessary for
# interactive non-login shells that are launched by something without my session
# info, e.g., the MacOS Dock.
if [ -z "$MY_BASH_ENV_IS_SET" ]; then
    CALLING_FROM_RC=true
    . ~/.bash_profile
    unset CALLING_FROM_RC
fi

# If not running interactively, don't do anything else
[[ $- != *i* ]] && return

HISTIGNORE='&:[ ]*:[bf]g:exit'  # Ignore duplicate entries and anything preceded by a space
HISTTIMEFORMAT='%F %T '	       # ISO date and time
HISTSIZE=-1		       # No limit
HISTFILESIZE=1000000
HISTCONTROL=erasedups

command -v emacsclient > /dev/null && export EDITOR=emacsclient

PRF="${HOME}/dotfiles/bash/"
[ -f "${PRF}aliases" ]      && . "${PRF}aliases"
[ -f "${PRF}prompt" ]       && . "${PRF}prompt"
[ -f "${PRF}completion" ]   && . "${PRF}completion"
unset PRF
