#!/hint/bash

# Linux
[ -f /etc/profile.d/bash_completion.sh ] && . /etc/profile.d/bash_completion.sh

# MacOS
[ -f /usr/local/etc/profile.d/bash_completion.sh ] && . /usr/local/etc/profile.d/bash_completion.sh

command -v kubectl >/dev/null 2>&1 && source <(kubectl completion bash)
command -v minikube >/dev/null 2>&1 && source <(minikube completion bash)

# https://github.com/cykerway/complete-alias/
# source ~/dotfiles/bash/complete-alias
# aliases=(k gco ga gb gc gd)
# for a in "${aliases[@]}"; do
#     complete -F _complete_alias "$a"
# done
# unset a aliases
