#!/hint/bash

if [ -z "$PATH_DEFAULT" ]; then
    export PATH_DEFAULT="$PATH"
fi

umask 002

export HISTIGNORE='&:[ ]*:[bf]g:exit'  # Ignore duplicate entries and anything preceded by a space
export HISTTIMEFORMAT='%F %T '
export HISTSIZE=100000000
export HISTFILESIZE=1000000
export HISTCONTROL=erasedups

export TEMP=/var/tmp
export TMP=${TEMP}

command -v emacsclient > /dev/null && export EDITOR=emacsclient
export LESS="-FiMXR"  # quit if one screen, case-insensitive search, verbose prompt, don't clear screen, allow colors
export LESSOPEN="| src-hilite-lesspipe.sh %s"
export PAGER=less
export PYTHONSTARTUP=~/.pythonrc
export SUDO_PROMPT="[sudo %u@%h] Password: "

export VIRTUAL_ENV_DISABLE_PROMPT=1  # so activate script doesn't modify prompt

# Add Kubernaut token using jq
if [ -f ~/.config/kubernaut/config.json ] && which jq >/dev/null ; then
    export KUBERNAUT_TOKEN=$(jq -r '.["kubernaut.io"]["token"]' < ~/.config/kubernaut/config.json)
fi

# Set up for Nix
if [ -e /home/ark3/.nix-profile/etc/profile.d/nix.sh ]; then
    . /home/ark3/.nix-profile/etc/profile.d/nix.sh
fi
