#!/hint/bash

if [ -z "$PATH_DEFAULT" ]; then
    export PATH_DEFAULT="$PATH"
fi

umask 022

export TEMP=/var/tmp
export TMP=${TEMP}
export LESS="-FiMXR"  # quit if one screen, case-insensitive search, verbose prompt, don't clear screen, allow colors
export PAGER=less
export PYTHONSTARTUP=~/.pythonrc
export SUDO_PROMPT="[sudo %u@%h] Password: "
export VIRTUAL_ENV_DISABLE_PROMPT=1  # so activate script doesn't modify prompt
